### ISSUE TITLE
Question for the decoder

### ISSUE THREAD

**Issue by SCUTykLin** [ToughStoneX/StyleDyRF#1]
Hello, great paper.
I am interested in the decoder. How do u design the decoder of this model. I found the decoder which u mention--"Learning linear transformations for fast image and video style transfer." will lead to blur results, the PSNR = 13-16.

Could you tell me about the architecture of the decoder? Thanks

**Comment by ToughStoneX** [comment]
The training code is released now. Please check the model architecture of the decoder in `models`.
